/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13PL3KQqtVjs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13PL3KQqtVjs= >>
// ----------- >>
public class Class1 {
// ----------- << class.extras@AAAAAAF13PL3KQqtVjs= >>
// ----------- >>
}