/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13Po5+DwUXpM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13Po5+DwUXpM= >>
// ----------- >>
public class Dyrektor extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF13PpZMDzE3TE= >>
    // ----------- >>
    private Uzytkownik ;

    // ----------- << attribute.annotations@AAAAAAF13Pp6s0Gjxeo= >>
    // ----------- >>
    private Faktura ;

    // ----------- << attribute.annotations@AAAAAAF13SR1OBPbzoc= >>
    // ----------- >>
    private PlanZajec ;

    public Uzytkownik get() {
        return ;
    }

    public Faktura get() {
        return ;
    }

    public PlanZajec get() {
        return ;
    }

    public void set(Uzytkownik ) {
        this. = ;
    }

    public void set(Faktura ) {
        this. = ;
    }

    public void set(PlanZajec ) {
        this. = ;
    }

    public void link(Uzytkownik _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Faktura _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(PlanZajec _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13Po5+DwUXpM= >>
// ----------- >>
}