/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vkuGt1Tr7y8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vkuGt1Tr7y8= >>
// ----------- >>
public class Dziennik {
    // ----------- << attribute.annotations@AAAAAAF1vmlykVZV11M= >>
    // ----------- >>
    private Map<User List<Byte>> Oceny;

    // ----------- << attribute.annotations@AAAAAAF1vnCQeFZiC/c= >>
    // ----------- >>
    private Map<User List<Boolean> Frekwencja;

    // ----------- << attribute.annotations@AAAAAAF1vnWAzFjBFpU= >>
    // ----------- >>
    private Nauczyciel ;

    private Map<User List<Byte>> getOceny() {
        return Oceny;
    }

    private Map<User List<Boolean> getFrekwencja() {
        return Frekwencja;
    }

    public Nauczyciel get() {
        return ;
    }

    private void setOceny(Map<User List<Byte>> Oceny) {
        this.Oceny = Oceny;
    }

    private void setFrekwencja(Map<User List<Boolean> Frekwencja) {
        this.Frekwencja = Frekwencja;
    }

    public void set(Nauczyciel ) {
        this. = ;
    }

    public void link(Nauczyciel _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF1vlNzulVNm5g= >>
    // ----------- >>
    public void dodajOcene() {
    // ----------- << method.body@AAAAAAF1vlNzulVNm5g= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vlRqwVVUdYY= >>
    // ----------- >>
    public void wstawNieobecnosc() {
    // ----------- << method.body@AAAAAAF1vlRqwVVUdYY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vmHJGFYx7ss= >>
    // ----------- >>
    public void liczFrekwencje() {
    // ----------- << method.body@AAAAAAF1vmHJGFYx7ss= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vmJV2FY4IkU= >>
    // ----------- >>
    public void liczSrednia() {
    // ----------- << method.body@AAAAAAF1vmJV2FY4IkU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF1vkuGt1Tr7y8= >>
// ----------- >>
}