/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13PmhcTJa1NY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13PmhcTJa1NY= >>
// ----------- >>
public class Ksiegowa extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF13Pn/yTghnQ0= >>
    // ----------- >>
    private Faktura ;

    public Faktura get() {
        return ;
    }

    public void set(Faktura ) {
        this. = ;
    }

    public void link(Faktura _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13PmhcTJa1NY= >>
// ----------- >>
}