/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vklIelSU/Ak= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vklIelSU/Ak= >>
// ----------- >>
public class Nauczyciel extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF1vljpwVWRhuE= >>
    // ----------- >>
    private String Specjalizacja;

    // ----------- << attribute.annotations@AAAAAAF1vnIj3VZwPqg= >>
    // ----------- >>
    private Uzytkownik ;

    // ----------- << attribute.annotations@AAAAAAF1vnPtvVfQZ3g= >>
    // ----------- >>
    private Klasa ;

    // ----------- << attribute.annotations@AAAAAAF1vnWAzFjCIJk= >>
    // ----------- >>
    private Dziennik ;

    // ----------- << attribute.annotations@AAAAAAF1vnW/eFk1kss= >>
    // ----------- >>
    private Test ;

    // ----------- << attribute.annotations@AAAAAAF13PaxHiSAiVM= >>
    // ----------- >>
    private Przedmiot ;

    // ----------- << attribute.annotations@AAAAAAF13RMpOr+5PTI= >>
    // ----------- >>
    private Przedmiot ;

    private String getSpecjalizacja() {
        return Specjalizacja;
    }

    public Uzytkownik get() {
        return ;
    }

    public Klasa get() {
        return ;
    }

    public Dziennik get() {
        return ;
    }

    public Test get() {
        return ;
    }

    public Przedmiot get() {
        return ;
    }

    public Przedmiot get() {
        return ;
    }

    private void setSpecjalizacja(String Specjalizacja) {
        this.Specjalizacja = Specjalizacja;
    }

    public void set(Uzytkownik ) {
        this. = ;
    }

    public void set(Klasa ) {
        this. = ;
    }

    public void set(Dziennik ) {
        this. = ;
    }

    public void set(Test ) {
        this. = ;
    }

    public void set(Przedmiot ) {
        this. = ;
    }

    public void set(Przedmiot ) {
        this. = ;
    }

    public void link(Uzytkownik _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Klasa _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Dziennik _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Test _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Przedmiot _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Przedmiot _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF1vklIelSU/Ak= >>
// ----------- >>
}