/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13N5PKCBMjhQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13N5PKCBMjhQ= >>
// ----------- >>
public class Ocena {
    // ----------- << attribute.annotations@AAAAAAF13N5l3yDQJn4= >>
    // ----------- >>
    private Integer wartosc;

    // ----------- << attribute.annotations@AAAAAAF13N6uLyGq1dc= >>
    // ----------- >>
    private String opis;

    // ----------- << attribute.annotations@AAAAAAF13O/PVk8Ym9E= >>
    // ----------- >>
    private Przedmiot ;

    // ----------- << attribute.annotations@AAAAAAF13O/efE+18XY= >>
    // ----------- >>
    private Rozwiazanie ;

    // ----------- << attribute.annotations@AAAAAAF13O/vaVBhedk= >>
    // ----------- >>
    private Test ;

    private Integer getWartosc() {
        return wartosc;
    }

    private String getOpis() {
        return opis;
    }

    public Przedmiot get() {
        return ;
    }

    public Rozwiazanie get() {
        return ;
    }

    public Test get() {
        return ;
    }

    private void setWartosc(Integer wartosc) {
        this.wartosc = wartosc;
    }

    private void setOpis(String opis) {
        this.opis = opis;
    }

    public void set(Przedmiot ) {
        this. = ;
    }

    public void set(Rozwiazanie ) {
        this. = ;
    }

    public void set(Test ) {
        this. = ;
    }

    public void link(Przedmiot _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Rozwiazanie _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Test _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13N5PKCBMjhQ= >>
// ----------- >>
}