/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13OQdCy78S+Y= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13OQdCy78S+Y= >>
// ----------- >>
public class Przedmiot {
    // ----------- << attribute.annotations@AAAAAAF13ORKwy+QDIk= >>
    // ----------- >>
    private String nazwa;

    // ----------- << attribute.annotations@AAAAAAF13O+jB04bkjM= >>
    // ----------- >>
    private Test ;

    // ----------- << attribute.annotations@AAAAAAF13O/PVk8XbX4= >>
    // ----------- >>
    private Ocena ;

    // ----------- << attribute.annotations@AAAAAAF13PaxHiR/kvA= >>
    // ----------- >>
    private Nauczyciel ;

    // ----------- << attribute.annotations@AAAAAAF13Q02WJVHY2g= >>
    // ----------- >>
    private Klasa ;

    // ----------- << attribute.annotations@AAAAAAF13RMpOr+4gYY= >>
    // ----------- >>
    private Nauczyciel ;

    private String getNazwa() {
        return nazwa;
    }

    public Test get() {
        return ;
    }

    public Ocena get() {
        return ;
    }

    public Nauczyciel get() {
        return ;
    }

    public Klasa get() {
        return ;
    }

    public Nauczyciel get() {
        return ;
    }

    private void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    public void set(Test ) {
        this. = ;
    }

    public void set(Ocena ) {
        this. = ;
    }

    public void set(Nauczyciel ) {
        this. = ;
    }

    public void set(Klasa ) {
        this. = ;
    }

    public void set(Nauczyciel ) {
        this. = ;
    }

    public void link(Test _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Ocena _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Nauczyciel _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Klasa _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Nauczyciel _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param data
    */

    // ----------- << method.annotations@AAAAAAF13Pu8YlJCP4o= >>
    // ----------- >>
    public void stworzTest(Date data) {
    // ----------- << method.body@AAAAAAF13Pu8YlJCP4o= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF13OQdCy78S+Y= >>
// ----------- >>
}