/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13Pzz7Fsvtfo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13Pzz7Fsvtfo= >>
// ----------- >>
public class Rozwiazanie {
    // ----------- << attribute.annotations@AAAAAAF13Sm8WWdo2Cg= >>
    // ----------- >>
    private List<String> odpowiedzi;

    // ----------- << attribute.annotations@AAAAAAF13P0piF76dRM= >>
    // ----------- >>
    private Uczeń ;

    // ----------- << attribute.annotations@AAAAAAF13P0xuV+2n4Y= >>
    // ----------- >>
    private Test ;

    // ----------- << attribute.annotations@AAAAAAF13O/efE+0gbE= >>
    // ----------- >>
    private Ocena ;

    public List<String> getOdpowiedzi() {
        return odpowiedzi;
    }

    public Uczeń get() {
        return ;
    }

    public Test get() {
        return ;
    }

    public Ocena get() {
        return ;
    }

    public void setOdpowiedzi(List<String> odpowiedzi) {
        this.odpowiedzi = odpowiedzi;
    }

    public void set(Uczeń ) {
        this. = ;
    }

    public void set(Test ) {
        this. = ;
    }

    public void set(Ocena ) {
        this. = ;
    }

    public void link(Uczeń _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Test _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Ocena _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13Pzz7Fsvtfo= >>
// ----------- >>
}