/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vloPdVWc1DY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vloPdVWc1DY= >>
// ----------- >>
public class Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF1vlqWSVXNOx0= >>
    // ----------- >>
    private String Id;

    // ----------- << attribute.annotations@AAAAAAF1vlrvgVXUQho= >>
    // ----------- >>
    private String Imie;

    // ----------- << attribute.annotations@AAAAAAF1vls4GVXcIoE= >>
    // ----------- >>
    private String Nazwisko;

    // ----------- << attribute.annotations@AAAAAAF1vlteqVXjFS4= >>
    // ----------- >>
    private String Adres;

    // ----------- << attribute.annotations@AAAAAAF1vnIj3VZvHVA= >>
    // ----------- >>
    private Nauczyciel ;

    // ----------- << attribute.annotations@AAAAAAF1vnI0W1a4fR0= >>
    // ----------- >>
    private Uczeń ;

    // ----------- << attribute.annotations@AAAAAAF13PpZLzzDrFw= >>
    // ----------- >>
    private Dyrektor ;

    private String getId() {
        return Id;
    }

    private String getImie() {
        return Imie;
    }

    private String getNazwisko() {
        return Nazwisko;
    }

    private String getAdres() {
        return Adres;
    }

    public Nauczyciel get() {
        return ;
    }

    public Uczeń get() {
        return ;
    }

    public Dyrektor get() {
        return ;
    }

    private void setId(String Id) {
        this.Id = Id;
    }

    private void setImie(String Imie) {
        this.Imie = Imie;
    }

    private void setNazwisko(String Nazwisko) {
        this.Nazwisko = Nazwisko;
    }

    private void setAdres(String Adres) {
        this.Adres = Adres;
    }

    public void set(Nauczyciel ) {
        this. = ;
    }

    public void set(Uczeń ) {
        this. = ;
    }

    public void set(Dyrektor ) {
        this. = ;
    }

    public void link(Nauczyciel _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Uczeń _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Dyrektor _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF1vloPdVWc1DY= >>
// ----------- >>
}