/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13SW0/Byyw3U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13SW0/Byyw3U= >>
// ----------- >>
public class Zajecie {
    // ----------- << attribute.annotations@AAAAAAF13SXRyB7700Y= >>
    // ----------- >>
    private PlanZajec ;

    // ----------- << attribute.annotations@AAAAAAF1vnPgFVeNNME= >>
    // ----------- >>
    private SpotkanieOnline ;

    // ----------- << attribute.annotations@AAAAAAF13ScITzws/SU= >>
    // ----------- >>
    private Klasa ;

    // ----------- << attribute.annotations@AAAAAAF13SdNTEVedHY= >>
    // ----------- >>
    private SalaLekcyjna ;

    public PlanZajec get() {
        return ;
    }

    public SpotkanieOnline get() {
        return ;
    }

    public Klasa get() {
        return ;
    }

    public SalaLekcyjna get() {
        return ;
    }

    public void set(PlanZajec ) {
        this. = ;
    }

    public void set(SpotkanieOnline ) {
        this. = ;
    }

    public void set(Klasa ) {
        this. = ;
    }

    public void set(SalaLekcyjna ) {
        this. = ;
    }

    public void link(PlanZajec _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(SpotkanieOnline _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Klasa _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(SalaLekcyjna _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13SW0/Byyw3U= >>
// ----------- >>
}