/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13PiNvC9YloI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13PiNvC9YloI= >>
// ----------- >>
public class Faktura {
    // ----------- << attribute.annotations@AAAAAAF13Piu8jA2hr4= >>
    // ----------- >>
    private Integer kwota;

    // ----------- << attribute.annotations@AAAAAAF13Pn/yTggTjU= >>
    // ----------- >>
    private Ksiegowa ;

    // ----------- << attribute.annotations@AAAAAAF13Pp6s0GiRwE= >>
    // ----------- >>
    private Dyrektor ;

    public Integer getKwota() {
        return kwota;
    }

    public Ksiegowa get() {
        return ;
    }

    public Dyrektor get() {
        return ;
    }

    public void setKwota(Integer kwota) {
        this.kwota = kwota;
    }

    public void set(Ksiegowa ) {
        this. = ;
    }

    public void set(Dyrektor ) {
        this. = ;
    }

    public void link(Ksiegowa _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Dyrektor _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF13SB03PGm+uA= >>
    // ----------- >>
    public void zatwierdz() {
    // ----------- << method.body@AAAAAAF13SB03PGm+uA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF13SCqGfL9cw4= >>
    // ----------- >>
    public void odrzuc() {
    // ----------- << method.body@AAAAAAF13SCqGfL9cw4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF13PiNvC9YloI= >>
// ----------- >>
}