/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13SOCTgb4PF8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13SOCTgb4PF8= >>
// ----------- >>
public class Planista extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF13SRsBhLVDfA= >>
    // ----------- >>
    private PlanZajec ;

    public PlanZajec get() {
        return ;
    }

    public void set(PlanZajec ) {
        this. = ;
    }

    public void link(PlanZajec _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13SOCTgb4PF8= >>
// ----------- >>
}