/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vlG/fVUYQMI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vlG/fVUYQMI= >>
// ----------- >>
public class SpotkanieOnline {
    // ----------- << attribute.annotations@AAAAAAF1vlb8IVWAlpk= >>
    // ----------- >>
    private String Id;

    // ----------- << attribute.annotations@AAAAAAF1vld+ClWH98M= >>
    // ----------- >>
    private String Nazwa;

    // ----------- << attribute.annotations@AAAAAAF1vnPgFVeMbE8= >>
    // ----------- >>
    private Zajecie ;

    private String getId() {
        return Id;
    }

    private String getNazwa() {
        return Nazwa;
    }

    public Zajecie get() {
        return ;
    }

    private void setId(String Id) {
        this.Id = Id;
    }

    private void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public void set(Zajecie ) {
        this. = ;
    }

    public void link(Zajecie _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF1vlUnHVVhwys= >>
    // ----------- >>
    public void utworz() {
    // ----------- << method.body@AAAAAAF1vlUnHVVhwys= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vlXHXFVrJxA= >>
    // ----------- >>
    public void dolacz() {
    // ----------- << method.body@AAAAAAF1vlXHXFVrJxA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vlZFPFV170E= >>
    // ----------- >>
    public void zakoncz() {
    // ----------- << method.body@AAAAAAF1vlZFPFV170E= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF1vlG/fVUYQMI= >>
// ----------- >>
}