/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vl4ftVX0XWE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vl4ftVX0XWE= >>
// ----------- >>
public class Test {
    // ----------- << attribute.annotations@AAAAAAF1vmRHgFY/HeA= >>
    // ----------- >>
    private String Id;

    // ----------- << attribute.annotations@AAAAAAF1vmR0iFZGBVQ= >>
    // ----------- >>
    private Date DataRozpoczecia;

    // ----------- << attribute.annotations@AAAAAAF1vmUxXlZN+Bo= >>
    // ----------- >>
    private Integer LimitCzasu;

    // ----------- << attribute.annotations@AAAAAAF13SotYWn3K08= >>
    // ----------- >>
    private List<String> pytania;

    // ----------- << attribute.annotations@AAAAAAF1vnW/eFk0TqQ= >>
    // ----------- >>
    private Nauczyciel ;

    // ----------- << attribute.annotations@AAAAAAF13O+jB04cdgc= >>
    // ----------- >>
    private Przedmiot ;

    // ----------- << attribute.annotations@AAAAAAF13O/vaVBgFlE= >>
    // ----------- >>
    private Ocena ;

    // ----------- << attribute.annotations@AAAAAAF13P0xuV+193s= >>
    // ----------- >>
    private Rozwiazanie ;

    private String getId() {
        return Id;
    }

    private Date getDataRozpoczecia() {
        return DataRozpoczecia;
    }

    private Integer getLimitCzasu() {
        return LimitCzasu;
    }

    public List<String> getPytania() {
        return pytania;
    }

    public Nauczyciel get() {
        return ;
    }

    public Przedmiot get() {
        return ;
    }

    public Ocena get() {
        return ;
    }

    public Rozwiazanie get() {
        return ;
    }

    private void setId(String Id) {
        this.Id = Id;
    }

    private void setDataRozpoczecia(Date DataRozpoczecia) {
        this.DataRozpoczecia = DataRozpoczecia;
    }

    private void setLimitCzasu(Integer LimitCzasu) {
        this.LimitCzasu = LimitCzasu;
    }

    public void setPytania(List<String> pytania) {
        this.pytania = pytania;
    }

    public void set(Nauczyciel ) {
        this. = ;
    }

    public void set(Przedmiot ) {
        this. = ;
    }

    public void set(Ocena ) {
        this. = ;
    }

    public void set(Rozwiazanie ) {
        this. = ;
    }

    public void link(Nauczyciel _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Przedmiot _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Ocena _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Rozwiazanie _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF1vl/NQFYjmIE= >>
    // ----------- >>
    public void utworz() {
    // ----------- << method.body@AAAAAAF1vl/NQFYjmIE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF1vmALuFYq3c0= >>
    // ----------- >>
    public void udostepnji() {
    // ----------- << method.body@AAAAAAF1vmALuFYq3c0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF1vl4ftVX0XWE= >>
// ----------- >>
}