/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1vkq1GFS/Hn4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1vkq1GFS/Hn4= >>
// ----------- >>
public class Uczeń extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF1vluU+lXqomo= >>
    // ----------- >>
    private Integer NumerLegitymacji;

    // ----------- << attribute.annotations@AAAAAAF1vnI0W1a5gFM= >>
    // ----------- >>
    private Uzytkownik ;

    // ----------- << attribute.annotations@AAAAAAF1vnbOpFwRuNc= >>
    // ----------- >>
    private Klasa ;

    // ----------- << attribute.annotations@AAAAAAF13P0piV77gC4= >>
    // ----------- >>
    private Rozwiazanie ;

    private Integer getNumerLegitymacji() {
        return NumerLegitymacji;
    }

    public Uzytkownik get() {
        return ;
    }

    public Klasa get() {
        return ;
    }

    public Rozwiazanie get() {
        return ;
    }

    private void setNumerLegitymacji(Integer NumerLegitymacji) {
        this.NumerLegitymacji = NumerLegitymacji;
    }

    public void set(Uzytkownik ) {
        this. = ;
    }

    public void set(Klasa ) {
        this. = ;
    }

    public void set(Rozwiazanie ) {
        this. = ;
    }

    public void link(Uzytkownik _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Klasa _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Rozwiazanie _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF1vkq1GFS/Hn4= >>
// ----------- >>
}