/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF13PYezx57jMM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF13PYezx57jMM= >>
// ----------- >>
public class Wozny extends Uzytkownik {
    // ----------- << attribute.annotations@AAAAAAF13Pb7ySkG2Io= >>
    // ----------- >>
    private SalaLekcyjna ;

    public SalaLekcyjna get() {
        return ;
    }

    public void set(SalaLekcyjna ) {
        this. = ;
    }

    public void link(SalaLekcyjna _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF13PYezx57jMM= >>
// ----------- >>
}